version: '2.0'

services:
  lms-web:
    build:
      context: ./lms-web
      dockerfile: dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8000}
        - NEXT_FRONTEND_URL=${NEXT_FRONTEND_URL:-http://localhost:3000}
        - NEXT_BACKEND_URL=${NEXT_BACKEND_URL:-http://localhost:8000}
        - NEXT_HOCTIEP_URL=${NEXT_HOCTIEP_URL}
        - NEXT_HOCTIEP_KEY=${NEXT_HOCTIEP_KEY}
        - NEXT_METABASE_INSTANCE_URL=${NEXT_METABASE_INSTANCE_URL}
        - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
        - AUTH_SECRET=${AUTH_SECRET}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8000}
      - NEXT_FRONTEND_URL=${NEXT_FRONTEND_URL:-http://localhost:3000}
      - NEXT_BACKEND_URL=${NEXT_BACKEND_URL:-http://localhost:8000}
      - NEXT_HOCTIEP_URL=${NEXT_HOCTIEP_URL}
      - NEXT_HOCTIEP_KEY=${NEXT_HOCTIEP_KEY}
      - NEXT_METABASE_INSTANCE_URL=${NEXT_METABASE_INSTANCE_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - AUTH_SECRET=${AUTH_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    restart: always
    # depends_on:
    #   - lms-backend
    # networks:
    #   - lms-network

  