version: '2.2'

services:
  backend-staging:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8002:8000"

    environment:
      # Metabase
      METABASE_SITE_URL: "https://metabase.hoctiep.com"
      METABASE_SECRET_KEY: "97bc8032360d9b6a4d3135a83f337d6ca659b8bb3ae0b2f4523c7921d21c7f8b"
      TIME_EXPIRATION: 10
      TIME_EXPIRATION_UNIT: 60
      ADMIN_DASHBOARD_ID: 6
      TEACHER_DASHBOARD_ID: 7
      STUDENT_DASHBOARD_ID: 5
      GROUP_STATS_DASHBOARD_ID: 9
      # Hoc tiep
      HOC_TIEP_BE_URL: "https://chat.hoctiep.com"
      HOC_TIEP_KEY: "sk-39a4e4963c28403da590fb94db37547a"
      BATCH_HANDLE_CHAT: 100
      # Database
      SOURCE_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/lms"
      TARGET_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/staging-lms"
      RETRY_COUNT: 0
      MAX_RETRIES: 3
      RETRY_INTERVAL: 60
      # Telegram bot
      TELEGRAM_BOT_TOKEN: "8082716944:AAEIsjVMmhwxibYbl_bOlR_f0lFNsRXQtDk"
      TELEGRAM_CHAT_ID: "-4657904264"
      # GOOGLE_CLIENT_SECRET: "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"
      # GOOGLE_CLIENT_ID: "755000991361-qbes7ah2m01ph8g94t6tr2g56fcvu4mp.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      GOOGLE_CLIENT_ID: "999861825007-ambav4mvkhjifoeh3fcc1pvivad1l9pm.apps.googleusercontent.com"
      GOOGLE_REDIRECT_URI: "https://staging-lms.hoctiep.com/callback"
      REACT_APP_FRONTEND_URL: "https://staging-lms.hoctiep.com"
      ENV: production      # Limit default
      REQUEST_LIMIT_DEFAULT: 5
      TOKEN_LIMT_DEFAULT: 1000

      # sqlite or postgresql
      # - DATABASE_URL=""
    # depends_on:
    #   - db
    restart: always
  
  cron-staging:
    build: 
      context: ./backend
      dockerfile: Dockerfile.cron
      args:
        CRON_SCHEDULE: 45 0 * * *
    environment:
      SOURCE_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/lms"
      TARGET_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/staging-lms"
      TELEGRAM_BOT_TOKEN: "8082716944:AAEIsjVMmhwxibYbl_bOlR_f0lFNsRXQtDk"
      TELEGRAM_CHAT_ID: "-4657904264"
      RETRY_COUNT: 0
      MAX_RETRIES: 3 # Số lần cố gắng kết nối db bị ngắt
      RETRY_INTERVAL: 30 # Khoảng thời gian nghỉ chờ kết nối lại

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - VITE_API_URL=http://backend:8000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  
 
  react-frontend-staging:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
      args:
        VITE_FRONTEND_URL: "https://staging-lms.hoctiep.com"
        VITE_BACKEND_URL: "https://staging-api-lms.hoctiep.com"
        VITE_GOOGLE_CLIENT_ID: "999861825007-ambav4mvkhjifoeh3fcc1pvivad1l9pm.apps.googleusercontent.com"
    ports:
      - "5003:3000"
    networks:
      - app_network_staging
    environment:
      - VITE_METABASE_INSTANCE_URL=https://metabase.hoctiep.com
      - VITE_BACKEND_URL=https://staging-api-lms.hoctiep.com
      # - VITE_GOOGLE_CLIENT_ID=755000991361-qbes7ah2m01ph8g94t6tr2g56fcvu4mp.apps.googleusercontent.com
      - VITE_GOOGLE_CLIENT_ID="999861825007-ambav4mvkhjifoeh3fcc1pvivad1l9pm.apps.googleusercontent.com"
    restart: always
networks:
  app_network_staging:
    external: false

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

 
