version: '2.2'

services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      # METABASE_SITE_URL: "http://localhost:5002"
      # METABASE_SECRET_KEY: "97bc8032360d9b6a4d3135a83f337d6ca659b8bb3ae0b2f4523c7921d21c7f8b"
      # TIME_EXPIRATION: 10
      # TIME_EXPIRATION_UNIT: 60
      # RESOURCE_IFRAME_URL: '{"dashboard": 33}'
      METABASE_SITE_URL: "https://metabase.hoctiep.com"
      METABASE_SECRET_KEY: "97bc8032360d9b6a4d3135a83f337d6ca659b8bb3ae0b2f4523c7921d21c7f8b"
      TIME_EXPIRATION: 10
      TIME_EXPIRATION_UNIT: 60
      ADMIN_DASHBOARD_ID: 3
      TEACHER_DASHBOARD_ID: 6
      STUDENT_DASHBOARD_ID: 5
      GROUP_STATS_DASHBOARD_ID: 9
      
      HOC_TIEP_BE_URL: "https://chat.hoctiep.com"
      HOC_TIEP_KEY: "sk-39a4e4963c28403da590fb94db37547a"
      BATCH_HANDLE_CHAT: 100
      SOURCE_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/webui"
      TARGET_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/lms"
      RETRY_COUNT: 0
      MAX_RETRIES: 3 # Số lần cố gắng kết nối db bị ngắt
      RETRY_INTERVAL: 30 # Khoảng thời gian nghỉ chờ kết nối lại
      TELEGRAM_BOT_TOKEN: "7728798987:AAG_C8gZolb7X06BXfru17pa3iB2cqR7iYc"
      TELEGRAM_CHAT_ID: "-1002386374933"
      GOOGLE_REDIRECT_URI: "http://localhost:5001/callback"
      GOOGLE_CLIENT_ID: "999861825007-ambav4mvkhjifoeh3fcc1pvivad1l9pm.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      REACT_APP_FRONTEND_URL: http://localhost:5001
      ENV: development      # Limit default
      REQUEST_LIMIT_DEFAULT: 5
      TOKEN_LIMT_DEFAULT: 1000

    networks:
      - app_network
      # sqlite or postgresql
      # - DATABASE_URL=""
    # depends_on:
    #   - db
    restart: always
  
  cron:
    build: 
      context: ./backend
      dockerfile: Dockerfile.cron
      args:
        CRON_SCHEDULE: "* * * * *"
    environment:
      METABASE_SITE_URL: "https://metabase.hoctiep.com"
      METABASE_SECRET_KEY: "97bc8032360d9b6a4d3135a83f337d6ca659b8bb3ae0b2f4523c7921d21c7f8b"
      TIME_EXPIRATION: 10
      TIME_EXPIRATION_UNIT: 60
      RESOURCE_IFRAME_URL: '{"dashboard": 3}'
      
      HOC_TIEP_BE_URL: "https://chat.hoctiep.com"
      HOC_TIEP_KEY: "sk-39a4e4963c28403da590fb94db37547a"
      BATCH_HANDLE_CHAT: 100
      SOURCE_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/webui"
      TARGET_DATABASE_URL: "postgresql://saokhue:Saokhuee123@139.180.220.97:5432/lms"
      RETRY_COUNT: 0
      MAX_RETRIES: 3 # Số lần cố gắng kết nối db bị ngắt
      RETRY_INTERVAL: 30 # Khoảng thời gian nghỉ chờ kết nối lại
      TELEGRAM_BOT_TOKEN: "7728798987:AAG_C8gZolb7X06BXfru17pa3iB2cqR7iYc"
      TELEGRAM_CHAT_ID: "-1002386374933"
      GOOGLE_REDIRECT_URI: "http://localhost:5001/callback"
      GOOGLE_CLIENT_ID: "999861825007-ambav4mvkhjifoeh3fcc1pvivad1l9pm.apps.googleusercontent.com"
      GOOGLE_CLIENT_SECRET: "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"
      REACT_APP_FRONTEND_URL: http://localhost:5001
      ENV: development      # Limit default
      REQUEST_LIMIT_DEFAULT: 5
      TOKEN_LIMT_DEFAULT: 1000
      

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - VITE_API_URL=http://backend:8000
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  
 
  react-frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_FRONTEND_URL: "http://localhost:5001"
        REACT_APP_BACKEND_URL: "http://localhost:8001"
        REACT_APP_GOOGLE_CLIENT_ID: "999861825007-ambav4mvkhjifoeh3fcc1pvivad1l9pm.apps.googleusercontent.com"
    container_name: react-frontend
    ports:
      - "5001:3000"
    networks:
      - app_network
    environment:
      REACT_APP_METABASE_INSTANCE_URL: http://metabase:3000
      REACT_APP_BACKEND_URL: http://localhost:8001
      REACT_APP_GOOGLE_CLIENT_ID: "999861825007-ambav4mvkhjifoeh3fcc1pvivad1l9pm.apps.googleusercontent.com"
      

    restart: always
networks:
  app_network:
    # external: true
    driver: bridge

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

 