"""add department_id in model

Revision ID: 12
Revises: 11
Create Date: 2025-04-20 20:25:41.443792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12'
down_revision = '11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('department_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'model', 'department', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'model', type_='foreignkey')
    op.drop_column('model', 'department_id')
    # ### end Alembic commands ###
