"""create model_group

Revision ID: 5
Revises: 4
Create Date: 2025-03-08 00:35:17.698374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5'
down_revision = '4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_group',
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('can_write', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_id', 'group_id')
    )
    op.create_index(op.f('ix_model_group_group_id'), 'model_group', ['group_id'], unique=False)
    op.create_index(op.f('ix_model_group_model_id'), 'model_group', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_group_model_id'), table_name='model_group')
    op.drop_index(op.f('ix_model_group_group_id'), table_name='model_group')
    op.drop_table('model_group')
    # ### end Alembic commands ###
