"""create rate limit filter

Revision ID: 7
Revises: 6
Create Date: 2025-03-13 21:21:30.742467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7'
down_revision = '6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_filter',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('token_limit', sa.BigInteger(), nullable=True),
    sa.Column('request_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('group_id', 'model_id')
    )
    op.create_index(op.f('ix_rate_limit_filter_group_id'), 'rate_limit_filter', ['group_id'], unique=False)
    op.create_index(op.f('ix_rate_limit_filter_model_id'), 'rate_limit_filter', ['model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rate_limit_filter_model_id'), table_name='rate_limit_filter')
    op.drop_index(op.f('ix_rate_limit_filter_group_id'), table_name='rate_limit_filter')
    op.drop_table('rate_limit_filter')
    # ### end Alembic commands ###
