"""add model default limit

Revision ID: 8
Revises: 7
Create Date: 2025-03-15 12:43:22.022734

"""
from alembic import op
import sqlalchemy as sa
import app


# revision identifiers, used by Alembic.
revision = '8'
down_revision = '7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model', sa.Column('default_limit', app.db.custom_types.json_field.JSONField(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model', 'default_limit')
    # ### end Alembic commands ###
