"""add_reset_hour_rate_limit

Revision ID: 9
Revises: 8
Create Date: 2025-03-17 00:25:33.783265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9'
down_revision = '8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate_limit_filter', sa.Column('reset_hours_value', sa.Integer(), server_default='24', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rate_limit_filter', 'reset_hours_value')
    # ### end Alembic commands ###
